# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 04e8eb76f2ebc8e8d54a80ab01b1545995e3445bc4fd087b32c8e4177d38b9857b8b799c36bdb52a79fd8afa013506795c2ae107728ace0c31acd6c045f228f5

test:
  secret_key_base: 86a3d9cc2df78c30824319ac64e4c8d51d6be3d1b8ca54e34b7173dc452dc154a4771eb912c935bc1805838c78a1ec75f2d3f41537c2b778aaf9329e19a73cf3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
